{% set name = "pymeshfix" %}
{% set version = "0.16.2" %}

package:
  name: pymeshfix
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 774721f332b42ee1fb45a2c301c4440307674513efa0b03ea45feb2efc9daac6
  patches:
    # This can be removed once the sdist is Python 3.11 compatible
    - force_cython.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython >=0.29.32
    - python
  host:
    - cython >=0.29.32
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymeshfix
  commands:   # [py!=311 or not win]
    - pip check  # [py!=311 or not win]
  requires:   # [py!=311 or not win]
    - pip        # [py!=311 or not win]

about:
  home: https://github.com/pyvista/pymeshfix
  summary: Python Wrapper for MeshFix to easily repair holes in surface meshes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
    - larsoner
