{% set name = "pymeshfix" %}
{% set version = "0.18.0" %}

package:
  name: pymeshfix
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c92dcccba6921fed6bdab0b6b8d232f4167407e7acbba959895c8340be7cf3a6
  patches:
    # This can be removed once the sdist is Python 3.11 compatible
    - force_cython.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython >=0.29.32                      # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - scikit-build-core
    - numpy
    - pip
    - setuptools
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0

test:
  imports:
    - pymeshfix
  commands:
    - pip check  # [(py!=312 and py!=311) or not win]
  requires:
    - pip        # [(py!=312 and py!=311) or not win]

about:
  home: https://github.com/pyvista/pymeshfix
  summary: Python Wrapper for MeshFix to easily repair holes in surface meshes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
    - larsoner
