{% set name = "pymeshfix" %}
{% set version = "0.17.0" %}

package:
  name: pymeshfix
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce809a1741aaf670a3df98cf6aaba15881223bd7230928effc021395455397c9
  patches:
    # This can be removed once the sdist is Python 3.11 compatible
    - force_cython.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython >=0.29.32
    - python
  host:
    - cython >=0.29.32
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0

test:
  imports:
    - pymeshfix
  commands:
    - pip check  # [(py!=312 and py!=311) or not win]
  requires:
    - pip        # [(py!=312 and py!=311) or not win]

about:
  home: https://github.com/pyvista/pymeshfix
  summary: Python Wrapper for MeshFix to easily repair holes in surface meshes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
    - larsoner
